---
title: "data_s10_example"
author: "Te-Hsuan Huang"
date: "2025-11-22"
output: github_document
---
```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

# Import the data
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

# fit a model
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

# Let's see the result
```{r, include=FALSE}
fit 
summary(fit)
coef(fit)
residuals(fit)
```

# let's look at the result better
```{r}
broom::glance(fit)
broom::tidy(fit)

fit |> 
  broom::tidy() |> 
  select(term, estimate, p.value) |> 
  mutate(term = str_replace(term, "borough", "Borough: ")) |> 
  knitr::kable(digits = 5)
```

# Be in control of factor
```{r}
nyc_airbnb=
  nyc_airbnb |> 
  mutate(
    borough=fct_infreq(borough),
    room_type=fct_infreq(room_type)
  )
```

* Order based on the frequency

# Diagnostic
```{r}
modelr::add_residuals(nyc_airbnb, fit)
```

# draw a plot for residual
```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = borough, y = resid)) + geom_violin()
```

# Another plot for residual
```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point()+
  facet_wrap(.~borough)
```

* Manhattan have wider distributions

# Hypothesis test

This do t-test by default, which is test for specific borough
```{r}
broom::tidy(fit)
```

ANOVA; the significance for whole borough
```{r}
fit_null = lm(price ~ stars , data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough, data = nyc_airbnb)

anova(fit_null, fit_alt) |> 
  broom::tidy()
```

